language: c

os:
  - linux
  - osx
  - windows

compiler:
  - gcc
  - clang

matrix:
  fast_finish: true
  allow_failures:
  - os: windows

env: UTIL_DIR=gwion-util

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-8

before_script:
  - git clone https://github.com/fennecdjay/gwion-util
  - cd gwion-util
  - if [ $(uname) = "Linux" ] || [ $(uname) = "Darwin" ];
    then make;
    else make.exe;
    fi
  - cd ..
  - if [ $(uname) = "Linux" ]; then if [ "$CC" = "gcc" ]; then export CC=gcc-8; fi; fi
#elif [ $(uname) = "Darwin" ]; then brew update; else sed -i 's#/#\\#g' Makefile; fi

script:
  - if [ $(uname) = "Linux" ] || [ $(uname) = "Darwin" ];
    then make;
    else make.exe;
    fi
