language: c

os:
  - linux
  - osx
  - windows

compiler:
  - gcc
  - clang

matrix:
  fast_finish: true

env: UTIL_DIR=gwion-util

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-8

before_script:
  - if [ $(uname) != "Linux" ] && [ $(uname) != "Darwin" ];
    then choco install make; alias gcc=gcc.exe;export CC="gcc.exe";
    export CFLAGS+="-DBUILD_ON_WINDOWS -D_XOPEN_SOURCE=700";
    fi
  - git clone https://github.com/fennecdjay/gwion-util
  - cd gwion-util
  - if [ $(uname) = "Linux" ] || [ $(uname) = "Darwin" ];
    then make;
    else make.exe;
    fi
  - cd ..
  - if [ $(uname) = "Linux" ]; then if [ "$CC" = "gcc" ]; then export CC=gcc-8; fi; fi
#    curl -L  http://downloads.sourceforge.net/project/gnuwin32/libgw32c/0.4/libgw32c-0.4-lib.zip > libgw32c.zip;
#    unzip libgw32c.zip -d libgw32c;
#    export CFLAGS+="-Ilibgw32c/include/glibc";
#elif [ $(uname) = "Darwin" ]; then brew update; else sed -i 's#/#\\#g' Makefile; fi

script:
  - if [ $(uname) = "Linux" ] || [ $(uname) = "Darwin" ];
    then make;
    else make.exe;
    fi
