name: Linux

on: [push, pull_request]

env:
  CFLAGS: -fsanitize=address -fno-omit-frame-pointer
  LDFLAGS: -fsanitize=address -fno-omit-frame-pointer

jobs:
  build:
    name: Linux ${{ matrix.cc }} ${{ matrix.double && 'double' || 'float'}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc: [gcc, clang]
        double: [0, 1]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build gwion-util
      uses: ./.github/workflows/util
      env:
        CC: ${{ matrix.cc }}
        USE_DOUBLE: ${{ matrix.double }}

    - name: build
      env:
         CC: ${{ matrix.cc }}        
         USE_DOUBLE: ${{ matrix.double }}
         UTIL_DIR: ./util
      run: make
