name: MacOs

on: [push, pull_request]

env:
  CFLAGS: -fsanitize=address -fno-omit-frame-pointer
  LDFLAGS: -fsanitize=address -fno-omit-frame-pointer

jobs:
  build:
    name: MacOS ${{ matrix.cc }} ${{ matrix.double && 'double' || 'float'}}
    runs-on: macos-latest
    env:
      CC: ${{ matrix.cc }}
      USE_DOUBLE: ${{ matrix.double }}
    strategy:
      matrix:
        cc: [gcc, clang]
        double: [0, 1]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Util lib
      uses: ./.github/workflows/util

    - name: Build
      run: make
      env:
         UTIL_DIR: ./util
