name: MacOs

on: [push, pull_request]

jobs:
  build:
    name: MacOS ${{ matrix.cc }} ${{ matrix.double && 'double' || 'float'}}
    runs-on: macos-latest
    strategy:
      matrix:
        cc: [gcc, clang]
        double: [0, 1]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build gwion-util
      uses: ./.github/workflows/util
      env:
        CC: ${{ matrix.cc }}
        USE_DOUBLE: ${{ matrix.double }}
        CFLAGS: -fsanitize=address -fno-omit-frame-pointer
        LDFLAGS: -fsanitize=address -fno-omit-frame-pointer

    - name: build
      env:
         CC: ${{ matrix.cc }}
         USE_DOUBLE: ${{ matrix.double }}
         CFLAGS: -fsanitize=address -fno-omit-frame-pointer
         LDFLAGS: -fsanitize=address -fno-omit-frame-pointer
         UTIL_DIR: ./util
      run: make
