name: Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    name:  Windows ${{ matrix.double && 'double' || 'float' }}
    env:
        CC: gcc
        USE_DOUBLE: ${{ matrix.double }}
        BUILD_ON_WINDOWS: 1
    strategy:
      matrix:
        double: [0, 1]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Util lib
      uses: ./.github/workflows/util

    - name: Build
      run: make
      env:
         UTIL_DIR: ./gwion-util
