name: Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest
    name:  Windows ${{ matrix.double }}
    strategy:
      matrix:
        double: [0, 1]
    steps:
    - name: deps
      env:
         CFLAGS: -DBUILD_ON_WINDOWS  
      run: |
        git clone https://github.com/fennecdjay/gwion-util util
        cd util
        make CC=$(which gcc) USE_DOUBLE=${{ matrix.double }}
    - name: clone
      run: git clone https://github.com/fennecdjay/gwion-ast ast
    - name: build
      env:
         CFLAGS: -DBUILD_ON_WINDOWS  
         USE_DOUBLE: ${{ matrix.double }}
      run: | 
        cd ast;
        make CC=$(which gcc) USE_DOUBLE=${{ matrix.double }}
