name: Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    name:  Windows ${{ matrix.double && 'double' || 'float' }}
    env:
        CC: gcc
        USE_DOUBLE: ${{ matrix.double }}
    strategy:
      matrix:
        double: [0, 1]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build gwion-util
      uses: ./.github/workflows/util
      env:

    - name: build
      run: make
      env:
         UTIL_DIR: ./util
