name: Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest
    name:  ${{ matrix.double && 'double' || '' }}
    strategy:
      matrix:
        double: [0, 1]
    steps:
    - name: deps
      run: |
        git clone https://github.com/fennecdjay/gwion-util util
        cd util
        make CC=$(which gcc) USE_DOUBLE=${{ matrix.double }}
    - name: clone
      run: git clone https://github.com/fennecdjay/gwion-ast ast
    - uses: actions/checkout@v1
    - name: build
      env:
         USE_DOUBLE: ${{ matrix.double }}
         CFLAGS: -fsanitize=address -fno-omit-frame-pointer
         LDFLAGS: -fsanitize=address -fno-omit-frame-pointer
      run: | 
        cd ast && make CC=$(which gcc) USE_DOUBLE=${{ matrix.double }}
