name: Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest
    name:  ${{ matrix.double && 'double' || '' }}
    strategy:
      matrix:
        double: [0, 1]
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: | 
        make CC=$(which gcc)
